name: Godot Windows Build With D3D12

on:
  workflow_dispatch

jobs:
  godot-windows-build-d3d12:
    runs-on: windows-latest
    name: Godot Windows Build With D3D12
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Install Scoop
        run: |
          Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
          Invoke-RestMethod -Uri https://get.scoop.sh | Invoke-Expression
      - name: Install Build Tools
        run: |
          scoop install gcc python scons make mingw
          7z x dxc_2024_03_07.zip -odxc -r
          7z x godot-nir-23.1.9.zip -ogodot-nir -r
          rename "winpixeventruntime.1.0.231030001.nupkg" "winpixeventruntime.1.0.231030001.zip"
          rename "microsoft.direct3d.d3d12.1.613.0.nupkg" "microsoft.direct3d.d3d12.1.613.0.zip"
          7z x winpixeventruntime.1.0.231030001.zip -opix -r
          7z x microsoft.direct3d.d3d12.1.613.0.zip -osdk -r
          cd pix
          gendef ./bin/x64/WinPixEventRuntime.dll
          dlltool --machine i386:x86-64 --no-leading-underscore -d WinPixEventRuntime.def -D WinPixEventRuntime.dll -l ./bin/x64/libWinPixEventRuntime.a
          cd ..
      - name: Running SCons And Build
        run: |
          scons platform=windows production=yes use_mingw=yes d3d12=yes dxc_path=./dxc mesa_libs=./godot-nir agility_sdk_path=./sdk pix_path=./pix
      - name: Upload Build 
        uses: actions/upload-artifact@v4.3.1
        with:
          path: ./bin
          retention-days: 7
          
          
          
     
          
            
